samples:
  - SRR12898293
  - SRR12898316
  - SRR24678051

minimap_index: /Users/callummacphillamy/Projects/variantCaller/input_data/reference/GCF_009914755.1_T2T-CHM13v2.0_genomic.mmi
reference: /Users/callummacphillamy/Projects/variantCaller/input_data/reference/GCF_009914755.1_T2T-CHM13v2.0_genomic.fa
